#!/usr/bin/env bash
# This script displays information about subdomains

# Function to display information about a subdomain
display_info() {
    domain=$1
    subdomain=$2
    info=$(dig +short "$subdomain.$domain")
    record_type="A"
    destination=$info
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Check if only domain is provided
if [ "$#" -eq 1 ]; then
    domain=$1
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    domain=$1
    subdomain=$2
    display_info "$domain" "$subdomain"
fi
