#!/usr/bin/env bash
#script to display information about subdomains.

# Function to display subdomain information
fetch_dns_info() {
    domain="$1"
    subdomain="$2"

    # Use dig to fetch DNS information for the subdomain
    dns_info=$(dig "$subdomain.$domain" +short)

    # Determine the record type (A or CNAME)
    record_type=$(echo "$dns_info" | awk '{ if (NF == 1) { print "A" } else { print "CNAME" } }')

    # Display the subdomain, record type, and destination
    echo "The subdomain $subdomain is a $record_type record and points to $dns_info"
}

# Check if the correct number of arguments is provided
if [ $# -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"

# If a subdomain is provided, fetch DNS info for that subdomain
if [ $# -eq 2 ]; then
    subdomain="$2"
    fetch_dns_info "$domain" "$subdomain"
else
    # If no subdomain provided, fetch DNS info for default subdomains
    fetch_dns_info "$domain" "www"
    fetch_dns_info "$domain" "lb-01"
    fetch_dns_info "$domain" "web-01"
    fetch_dns_info "$domain" "web-02"
fi
