#!/usr/bin/env bash
# Install nginx web server
sudo  apt-get -y update
sudo apt-get -y install nginx
sudo sed -i 's/^\(.*listen\s*80\s*;\)/\1/' /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
sudo service start nginx
