#!/usr/bin/env bash
# installing nginx on web server and setting up redirection

# Update the package lists for upgrades and new package installations
apt-get -y update

# Install nginx
apt-get -y install nginx

# Create a custom homepage
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure nginx to listen on port 80
sed -i 's/8080/80/g' /etc/nginx/sites-available/default

# Set up redirection for /redirect_me to another page
echo "server {
    listen 80;
    server_name _;
    location = /redirect_me/ {
        return 301 https://www.fosstechnix.com/how-to-install-nginx-on-ubuntu-22-04;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx to apply the changes
service nginx restart
