#!/usr/bin/env bash
# Script to create a redirection

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx

sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
sudo chown -R "$USER":"$USER" /usr/share/nginx/html/

echo "Hello World" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

sudo sed -i "s|#error_page 404 /404.html;|error_page 404 /404.html;|" /etc/nginx/sites-available/default
sudo sed -i "s|#location = /404.html {|location = /404.html {|" /etc/nginx/sites-available/default
sudo sed -i "s|#  root /usr/share/nginx/html;|  root /usr/share/nginx/html;|" /etc/nginx/sites-available/default
sudo sed -i "s|#  internal;|  internal;|" /etc/nginx/sites-available/default
sudo sed -i "s|#}|}|" /etc/nginx/sites-available/default

sudo service nginx restart

