#!/usr/bin/env bash
# Install Nginx on a web server to specifications
sudo  apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www /etc/nginx/sites-available
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /redirect_me {
        return 301 https://www.fosstechnix.com/how-to-install-nginx-on-ubuntu-22-04;
    }

    error_page 404 /custom_404.html;

    add_header X-Served-By $HOSTNAME;
}" > /etc/nginx/sites-available/default
sudo service nginx restart
