#!/usr/bin/env bash
# Create a script to configure nginx on a new server
# Configure nginx to have a custom header

sudo sed -i '/server_name _/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
