#!/usr/bin/env bash
# configures a server to listen to port 80

sudo apt-get -y install nginx
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
