#!/usr/bin/env bash
# Bash script displays all active IPv4s on machine

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
# ifconfig | grep "inet addr" | cut -d":" -f2 | cut -d" " -f1
